## 데이터 불러오기

In [46]:
import pandas as pd
import numpy as np

dt = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/pre_data/final_data.csv')
rf = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/pre_data/rf_fill.csv')
dt2022 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/water_data/data_2022.csv')

In [47]:
dt2022.columns

Index(['ymdhm', 'swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level',
       'wl_1018662', 'fw_1018662', 'wl_1018680', 'fw_1018680', 'wl_1018683',
       'fw_1018683', 'wl_1019630', 'fw_1019630'],
      dtype='object')

In [48]:
dt2022 = dt2022[['ymdhm', 'swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level',
       'wl_1018662', 'fw_1018662', 'wl_1018680', 'wl_1018683',
       'fw_1018683', 'wl_1019630', 'fw_1019630']]

In [49]:
dt2022[dt2022['ymdhm'] == '2022-06-01 00:00']

ymdhm    swl    inf     sfw   ecpc  tototf  tide_level  \
4464  2022-06-01 00:00  25.19  140.6  218.36  25.64   140.6       162.0   

      wl_1018662  fw_1018662  wl_1018680  wl_1018683  fw_1018683  wl_1019630  \
4464         0.0       269.4         0.0         0.0        8.23         0.0   

      fw_1019630  
4464      471.08

In [50]:
dt2022 = dt2022[4464:]
dt2022.head(3)

ymdhm    swl     inf     sfw   ecpc  tototf  tide_level  \
4464  2022-06-01 00:00  25.19  140.60  218.36  25.64  140.60       162.0   
4465  2022-06-01 00:10  25.19  140.78  218.36  25.64  140.78       151.0   
4466  2022-06-01 00:20  25.20  755.90  218.73  25.27  140.90       141.0   

      wl_1018662  fw_1018662  wl_1018680  wl_1018683  fw_1018683  wl_1019630  \
4464         0.0      269.40         0.0         0.0        8.23         0.0   
4465         0.0      280.22         0.0         0.0       28.82         0.0   
4466         0.0      296.87         0.0         0.0       12.35         0.0   

      fw_1019630  
4464      471.08  
4465      449.12  
4466      417.17

In [51]:
dt.head()

ymdhm     swl    inf     sfw   ecpc  tototf  tide_level  \
0  2012-05-01 0:00  24.800  555.0  219.07  24.93   555.0       445.0   
1  2012-05-01 0:10  24.794  464.6  218.86  25.15   562.9       449.0   
2  2012-05-01 0:20  24.789  478.1  218.69  25.31   576.4       451.0   
3  2012-05-01 0:30  24.789  464.8  218.69  25.31   563.1       452.0   
4  2012-05-01 0:40  24.789  478.1  218.69  25.31   576.4       450.0   

   wl_1018662  fw_1018662  wl_1018680  wl_1018683  fw_1018683  wl_1019630  \
0       310.7      469.05       300.2       290.0      729.80       275.3   
1       314.7      498.00       300.2       290.0      731.48       275.3   
2       313.7      490.68       301.2       290.0      726.42       275.3   
3       311.7      476.21       301.2       290.0      726.42       276.3   
4       311.7      476.21       301.2       291.0      707.17       277.3   

   fw_1019630  rf_10184100  rf_10184110  rf_10184140  fw_1018610  fw_1018640  
0      540.18          0.0          0.0          0.0      497.47     2054.51  
1      540.18          0.0          0.0          0.0      497.47     2054.51  
2      540.18          0.0          0.0          0.0      497.47     2054.51  
3      552.17          0.0          0.0          0.0      497.47     2054.51  
4      564.29          0.0          0.0          0.0      497.47     2054.51

In [52]:
dt.tail()

ymdhm    swl     inf     sfw   ecpc  tototf  tide_level  \
276331  2022-07-18 23:10:00  25.04  259.23  212.86  31.14  259.23       510.0   
276332  2022-07-18 23:20:00  25.04  260.46  212.86  31.14  260.46       492.0   
276333  2022-07-18 23:30:00  25.04  259.37  212.86  31.14  259.37       475.0   
276334  2022-07-18 23:40:00  25.04  259.13  212.86  31.14  259.13       458.0   
276335  2022-07-18 23:50:00  25.04  258.16  212.86  31.14  258.16       442.0   

        wl_1018662  fw_1018662  wl_1018680  wl_1018683  fw_1018683  \
276331       288.0      319.84       295.0       299.0     -456.41   
276332       287.0      314.01       303.0       304.0     -717.30   
276333       299.0      387.55       307.0       309.0     -843.37   
276334       309.0      454.91       311.0       314.0    -1023.37   
276335       326.0      582.21       314.0       317.0    -1049.44   

        wl_1019630  fw_1019630  rf_10184100  rf_10184110  rf_10184140  \
276331       306.0      974.40          0.0          0.0          0.0   
276332       308.0     1006.88          0.0          0.0          0.0   
276333       310.0     1039.90          0.0          0.0          0.0   
276334       312.0     1073.46          0.0          0.0          0.0   
276335       313.0     1090.45          0.0          0.0          0.0   

        fw_1018610  fw_1018640  
276331      255.36      315.64  
276332      255.36      348.44  
276333      255.36      319.74  
276334      255.36      323.84  
276335      255.36      315.64

In [53]:
rf_2012 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2012.csv')
rf_2013 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2013.csv')
rf_2014 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2014.csv')
rf_2015 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2015.csv')
rf_2016 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2016.csv')
rf_2017 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2017.csv')
rf_2018 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2018.csv')
rf_2019 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2019.csv')
rf_2020 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2020.csv')
rf_2021 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2021.csv')
rf_2022 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/rf_data/rf_2022.csv')

In [54]:
rf = pd.concat([rf_2012, rf_2013, rf_2014, rf_2015, rf_2016, rf_2017, rf_2018, rf_2019, rf_2020, rf_2021, rf_2022])
rf.shape

(276336, 4)

In [55]:
rf = rf.reset_index()
rf.head()

index             ymdhm  rf_10184100  rf_10184110  rf_10184140
0      0  2012-05-01 00:00          0.0          0.0          0.0
1      1  2012-05-01 00:10          0.0          0.0          0.0
2      2  2012-05-01 00:20          0.0          0.0          0.0
3      3  2012-05-01 00:30          0.0          0.0          0.0
4      4  2012-05-01 00:40          0.0          0.0          0.0

In [56]:
rf = rf[['rf_10184100', 'rf_10184110', 'rf_10184140']]

In [57]:
total = pd.concat([dt, rf], axis=1)
total.head(3)

ymdhm     swl    inf     sfw   ecpc  tototf  tide_level  \
0  2012-05-01 0:00  24.800  555.0  219.07  24.93   555.0       445.0   
1  2012-05-01 0:10  24.794  464.6  218.86  25.15   562.9       449.0   
2  2012-05-01 0:20  24.789  478.1  218.69  25.31   576.4       451.0   

   wl_1018662  fw_1018662  wl_1018680  ...  wl_1019630  fw_1019630  \
0       310.7      469.05       300.2  ...       275.3      540.18   
1       314.7      498.00       300.2  ...       275.3      540.18   
2       313.7      490.68       301.2  ...       275.3      540.18   

   rf_10184100  rf_10184110  rf_10184140  fw_1018610  fw_1018640  rf_10184100  \
0          0.0          0.0          0.0      497.47     2054.51          0.0   
1          0.0          0.0          0.0      497.47     2054.51          0.0   
2          0.0          0.0          0.0      497.47     2054.51          0.0   

   rf_10184110  rf_10184140  
0          0.0          0.0  
1          0.0          0.0  
2          0.0          0.0  

[3 rows x 22 columns]

## 정답 데이터 불러오기

In [58]:
ans = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/ans_data/total_ans.csv')
ans = ans.iloc[:,1:]
ans.head()

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0         279       276.0       274.0       269.0
1         281       277.0       274.0       267.0
2         284       277.0       274.0       264.0
3         285       277.0       274.0       261.0
4         284       278.0       274.0       259.0

## train, test 나누기

In [59]:
target = total[['wl_1018662', 'wl_1018680', 'wl_1018683', 'wl_1019630']]
data = total.drop(columns = ['wl_1018662', 'wl_1018680', 'wl_1018683', 'wl_1019630'])

In [60]:
data.index += 1

total = pd.concat([data, target], axis=1)

total = total.iloc[1:-1]

target = total[['wl_1018662', 'wl_1018680', 'wl_1018683', 'wl_1019630']]
data = total.drop(columns = ['wl_1018662', 'wl_1018680', 'wl_1018683', 'wl_1019630'])

In [61]:
data = data.reset_index()
data.head()

index            ymdhm     swl    inf     sfw   ecpc  tototf  tide_level  \
0      1  2012-05-01 0:00  24.800  555.0  219.07  24.93   555.0       445.0   
1      2  2012-05-01 0:10  24.794  464.6  218.86  25.15   562.9       449.0   
2      3  2012-05-01 0:20  24.789  478.1  218.69  25.31   576.4       451.0   
3      4  2012-05-01 0:30  24.789  464.8  218.69  25.31   563.1       452.0   
4      5  2012-05-01 0:40  24.789  478.1  218.69  25.31   576.4       450.0   

   fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184110  rf_10184140  \
0      469.05      729.80      540.18          0.0          0.0          0.0   
1      498.00      731.48      540.18          0.0          0.0          0.0   
2      490.68      726.42      540.18          0.0          0.0          0.0   
3      476.21      726.42      552.17          0.0          0.0          0.0   
4      476.21      707.17      564.29          0.0          0.0          0.0   

   fw_1018610  fw_1018640  rf_10184100  rf_10184110  rf_10184140  
0      497.47     2054.51          0.0          0.0          0.0  
1      497.47     2054.51          0.0          0.0          0.0  
2      497.47     2054.51          0.0          0.0          0.0  
3      497.47     2054.51          0.0          0.0          0.0  
4      497.47     2054.51          0.0          0.0          0.0

In [62]:
data = data.drop(columns = 'index')

In [63]:
data.tail()

ymdhm    swl     inf     sfw   ecpc  tototf  tide_level  \
276330  2022-07-18 23:00:00  25.04  865.96  212.86  31.14  259.30       528.0   
276331  2022-07-18 23:10:00  25.04  259.23  212.86  31.14  259.23       510.0   
276332  2022-07-18 23:20:00  25.04  260.46  212.86  31.14  260.46       492.0   
276333  2022-07-18 23:30:00  25.04  259.37  212.86  31.14  259.37       475.0   
276334  2022-07-18 23:40:00  25.04  259.13  212.86  31.14  259.13       458.0   

        fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184110  \
276330      319.84       25.27      926.70          0.0          0.0   
276331      319.84     -456.41      974.40          0.0          0.0   
276332      314.01     -717.30     1006.88          0.0          0.0   
276333      387.55     -843.37     1039.90          0.0          0.0   
276334      454.91    -1023.37     1073.46          0.0          0.0   

        rf_10184140  fw_1018610  fw_1018640  rf_10184100  rf_10184110  \
276330          0.0      255.36      282.85          0.0          0.0   
276331          0.0      255.36      315.64          0.0          0.0   
276332          0.0      255.36      348.44          0.0          0.0   
276333          0.0      255.36      319.74          0.0          0.0   
276334          0.0      255.36      323.84          0.0          0.0   

        rf_10184140  
276330          0.0  
276331          0.0  
276332          0.0  
276333          0.0  
276334          0.0

In [64]:
data[data['ymdhm'] == '2022-06-01 00:00:00']

ymdhm    swl    inf     sfw   ecpc  tototf  tide_level  \
269424  2022-06-01 00:00:00  25.19  140.6  218.36  25.64   140.6       162.0   

        fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184110  \
269424       269.4        8.23      471.08          0.0          0.0   

        rf_10184140  fw_1018610  fw_1018640  rf_10184100  rf_10184110  \
269424          0.0      135.52      156.74          0.0          0.0   

        rf_10184140  
269424          0.0

In [65]:
train_data = data[:269423]
test_data = data[269423:]

train_target = target[:269423]
test_target = target[269423:]

print(train_data.shape)
print(test_data.shape)
print(train_target.shape)
print(test_target.shape)

(269423, 18)
(6912, 18)
(269423, 4)
(6912, 4)


In [66]:
#test_data = test_data.fillna(method='ffill')

In [67]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6912 entries, 269423 to 276334
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   ymdhm        6912 non-null   object 
 1   swl          6912 non-null   float64
 2   inf          6912 non-null   float64
 3   sfw          6912 non-null   float64
 4   ecpc         6912 non-null   float64
 5   tototf       6912 non-null   float64
 6   tide_level   6912 non-null   float64
 7   fw_1018662   6912 non-null   float64
 8   fw_1018683   6912 non-null   float64
 9   fw_1019630   6912 non-null   float64
 10  rf_10184100  6912 non-null   float64
 11  rf_10184110  6912 non-null   float64
 12  rf_10184140  6912 non-null   float64
 13  fw_1018610   6912 non-null   float64
 14  fw_1018640   6912 non-null   float64
 15  rf_10184100  6912 non-null   float64
 16  rf_10184110  6912 non-null   float64
 17  rf_10184140  6912 non-null   float64
dtypes: float64(17), object(1)
memory usage: 9

## 데이터 스케일링 (MinMax)

In [68]:
train_data = train_data.reset_index()

In [69]:
train_data.columns

Index(['index', 'ymdhm', 'swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level',
       'fw_1018662', 'fw_1018683', 'fw_1019630', 'rf_10184100', 'rf_10184110',
       'rf_10184140', 'fw_1018610', 'fw_1018640', 'rf_10184100', 'rf_10184110',
       'rf_10184140'],
      dtype='object')

In [70]:
train_data2 = train_data[['swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level',
       'fw_1018662', 'fw_1018683', 'fw_1019630', 'rf_10184100', 'rf_10184110',
       'rf_10184140']]

In [71]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

# MinMaxScaler 선언 및 Fitting
mMscaler1 = StandardScaler()
mMscaler1.fit(train_data2)

# 데이터 변환
mMscaled_data = mMscaler1.transform(train_data2)

# 데이터 프레임으로 저장
train_data_sc = pd.DataFrame(mMscaled_data, columns=train_data2.columns)

In [72]:
mMscaler2 = StandardScaler()
mMscaler2.fit(train_target)

mMscaled_target = mMscaler2.transform(train_target)

train_target_sc = pd.DataFrame(mMscaled_target, columns=train_target.columns)

In [73]:
train_data_sc.head(2)

swl       inf       sfw      ecpc    tototf  tide_level  fw_1018662  \
0 -1.928302  0.007233 -0.057114  0.057056  0.015983    0.567597   -0.257380   
1 -1.969407 -0.074831 -0.078281  0.079231  0.023169    0.590638   -0.230234   

   fw_1018683  fw_1019630  rf_10184100  rf_10184100  rf_10184110  rf_10184110  \
0    0.097819   -0.360901    -0.098832    -0.098832    -0.101732    -0.101732   
1    0.099046   -0.360901    -0.098832    -0.098832    -0.101732    -0.101732   

   rf_10184140  rf_10184140  
0    -0.097955    -0.097955  
1    -0.097955    -0.097955

In [74]:
train_target_sc.head(2)

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0   -0.189202   -0.233010   -0.352832   -0.480885
1   -0.202355   -0.218113   -0.352832   -0.480885

In [75]:
train_data = pd.concat([train_data['ymdhm'], train_data_sc], axis=1)
train_data.head(2)

ymdhm       swl       inf       sfw      ecpc    tototf  \
0  2012-05-01 0:00 -1.928302  0.007233 -0.057114  0.057056  0.015983   
1  2012-05-01 0:10 -1.969407 -0.074831 -0.078281  0.079231  0.023169   

   tide_level  fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184100  \
0    0.567597   -0.257380    0.097819   -0.360901    -0.098832    -0.098832   
1    0.590638   -0.230234    0.099046   -0.360901    -0.098832    -0.098832   

   rf_10184110  rf_10184110  rf_10184140  rf_10184140  
0    -0.101732    -0.101732    -0.097955    -0.097955  
1    -0.101732    -0.101732    -0.097955    -0.097955

In [76]:
test_data = test_data.reset_index()

In [77]:
test_data2 = test_data[['swl', 'inf', 'sfw', 'ecpc', 'tototf', 'tide_level',
       'fw_1018662', 'fw_1018683', 'fw_1019630', 'rf_10184100', 'rf_10184110',
       'rf_10184140']]

In [78]:
mMscaled_test = mMscaler1.transform(test_data2)
test_data_sc = pd.DataFrame(mMscaled_test, columns=test_data2.columns)

test_data = pd.concat([test_data['ymdhm'], test_data_sc], axis=1)
test_data.head(2)

ymdhm       swl       inf       sfw      ecpc    tototf  \
0     2022-05-31 23:50  0.743574 -0.368992 -0.128678  0.128622 -0.360982   
1  2022-06-01 00:00:00  0.743574 -0.368956 -0.128678  0.128622 -0.360946   

   tide_level  fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184100  \
0   -0.999219    -0.44459   -0.384048   -0.401612    -0.098832    -0.098832   
1   -1.062583    -0.44459   -0.429232   -0.409471    -0.098832    -0.098832   

   rf_10184110  rf_10184110  rf_10184140  rf_10184140  
0    -0.101732    -0.101732    -0.097955    -0.097955  
1    -0.101732    -0.101732    -0.097955    -0.097955

## 모델링 #1 - Random Forest

In [79]:
train_data = train_data.set_index('ymdhm')
test_data = test_data.set_index('ymdhm')
train_data.head()

swl       inf       sfw      ecpc    tototf  tide_level  \
ymdhm                                                                           
2012-05-01 0:00 -1.928302  0.007233 -0.057114  0.057056  0.015983    0.567597   
2012-05-01 0:10 -1.969407 -0.074831 -0.078281  0.079231  0.023169    0.590638   
2012-05-01 0:20 -2.003662 -0.062576 -0.095416  0.095359  0.035448    0.602159   
2012-05-01 0:30 -2.003662 -0.074649 -0.095416  0.095359  0.023351    0.607919   
2012-05-01 0:40 -2.003662 -0.062576 -0.095416  0.095359  0.035448    0.596399   

                 fw_1018662  fw_1018683  fw_1019630  rf_10184100  rf_10184100  \
ymdhm                                                                           
2012-05-01 0:00   -0.257380    0.097819   -0.360901    -0.098832    -0.098832   
2012-05-01 0:10   -0.230234    0.099046   -0.360901    -0.098832    -0.098832   
2012-05-01 0:20   -0.237098    0.095350   -0.360901    -0.098832    -0.098832   
2012-05-01 0:30   -0.250666    0.095350   -0.352473    -0.098832    -0.098832   
2012-05-01 0:40   -0.250666    0.081289   -0.343954    -0.098832    -0.098832   

                 rf_10184110  rf_10184110  rf_10184140  rf_10184140  
ymdhm                                                                
2012-05-01 0:00    -0.101732    -0.101732    -0.097955    -0.097955  
2012-05-01 0:10    -0.101732    -0.101732    -0.097955    -0.097955  
2012-05-01 0:20    -0.101732    -0.101732    -0.097955    -0.097955  
2012-05-01 0:30    -0.101732    -0.101732    -0.097955    -0.097955  
2012-05-01 0:40    -0.101732    -0.101732    -0.097955    -0.097955

In [80]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=2, shuffle=True)

from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_jobs=-1)

params = {
    "n_estimators" : [150],
    #"max_depth" : (3,5,10,15),
    #"max_features" : (3,5,10)
    'max_depth':[12,14,16],
    'min_samples_leaf':[4,6,8],
    'min_samples_split':[4,6,8]
}

In [81]:
from sklearn.model_selection import GridSearchCV
grid_cv = GridSearchCV(rf,
                       param_grid=params,
                       cv = kfold,
                       n_jobs=-1)

In [ ]:
grid_cv.fit(train_data,train_target_sc)

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:705: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning


GridSearchCV(cv=KFold(n_splits=2, random_state=None, shuffle=True),
             estimator=RandomForestRegressor(n_jobs=-1), n_jobs=-1,
             param_grid={'max_depth': [12, 14, 16],
                         'min_samples_leaf': [4, 6, 8],
                         'min_samples_split': [4, 6, 8],
                         'n_estimators': [150]})

In [ ]:
grid_cv.best_estimator_

RandomForestRegressor(max_depth=16, min_samples_leaf=4, min_samples_split=4,
                      n_estimators=150, n_jobs=-1)

In [ ]:
model_rf = grid_cv.best_estimator_
model_rf.fit(train_data, train_target_sc)

RandomForestRegressor(max_depth=16, min_samples_leaf=4, min_samples_split=4,
                      n_estimators=150, n_jobs=-1)

In [ ]:
y_pred = model_rf.predict(test_data)

In [ ]:
y_pred

array([[-0.66480369, -0.63518488, -0.61699143, -0.58917239],
       [-0.65926665, -0.6516927 , -0.62696035, -0.61069089],
       [-0.6310416 , -0.69477043, -0.66875974, -0.6451003 ],
       ...,
       [-0.46968507, -0.13273553, -0.08879669,  0.19939625],
       [-0.25966183, -0.12363659, -0.007832  ,  0.22002764],
       [-0.09752934, -0.0240881 ,  0.0509363 ,  0.23839314]])

In [ ]:
inverse_transformed_X = mMscaler2.inverse_transform(y_pred) ## 원 데이터의 스케일로 변환
inverse_transformed_X

array([[278.54148109, 273.20260008, 273.22724291, 269.75913529],
       [278.96244492, 272.09445529, 272.59426766, 268.65807117],
       [281.10830783, 269.20271322, 269.94022125, 266.89740149],
       ...,
       [293.37574087, 306.93125594, 306.76489367, 310.10882188],
       [309.34315173, 307.54205396, 311.90573482, 311.16449441],
       [321.66957908, 314.22459166, 315.63722005, 312.10422475]])

In [ ]:
pred = pd.DataFrame(inverse_transformed_X, columns=train_target.columns)
pred.head()

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0  278.541481  273.202600  273.227243  269.759135
1  278.962445  272.094455  272.594268  268.658071
2  281.108308  269.202713  269.940221  266.897401
3  284.492298  273.705872  272.121975  263.995943
4  285.055168  272.889813  271.473817  261.065801

In [ ]:
# RMSE
from sklearn.metrics import mean_squared_error 

MSE = mean_squared_error(ans, pred) 
np.sqrt(MSE)

4.023775436181926

In [ ]:
print(np.sqrt(mean_squared_error(ans['wl_1018662'], pred['wl_1018662'])))
print(np.sqrt(mean_squared_error(ans['wl_1018680'], pred['wl_1018680'])))
print(np.sqrt(mean_squared_error(ans['wl_1018683'], pred['wl_1018683'])))
print(np.sqrt(mean_squared_error(ans['wl_1019630'], pred['wl_1019630'])))

3.7849910976815075
5.625126158298042
3.833710271777951
2.0242378044714266


In [ ]:
pred.to_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/submission/sub_rf.csv')

## 모델링 #2 - AdaBoost

In [ ]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

ada_reg = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=1), n_estimators=200, learning_rate=0.5
)
ada_reg.fit(train_data,train_target_sc['wl_1018662'])

In [ ]:
pred_662 = ada_reg.predict(test_data)
pred_662

In [ ]:
pred_662 = pred_662.reshape(-1,1)
pred_662

In [ ]:
ada_reg = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=1), n_estimators=200, learning_rate=0.5
)
ada_reg.fit(train_data,train_target_sc['wl_1018680'])

In [ ]:
pred_680 = ada_reg.predict(test_data)
pred_680

In [ ]:
ada_reg = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=1), n_estimators=200, learning_rate=0.5
)
ada_reg.fit(train_data,train_target_sc['wl_1018683'])

In [ ]:
pred_683 = ada_reg.predict(test_data)
pred_683

In [ ]:
ada_reg = AdaBoostRegressor(
    DecisionTreeRegressor(max_depth=1), n_estimators=200, learning_rate=0.5
)
ada_reg.fit(train_data,train_target_sc['wl_1019630'])

In [ ]:
pred_630 = ada_reg.predict(test_data)
pred_630

In [ ]:
pred_ada = np.stack((pred_662, pred_680, pred_683, pred_630), axis=1)
pred_ada

In [ ]:
inverse_ada = mMscaler2.inverse_transform(pred_ada) ## 원 데이터의 스케일로 변환
inverse_ada

In [ ]:
pred_ada = pd.DataFrame(inverse_ada, columns=train_target.columns)
pred_ada.head()

In [ ]:
# RMSE
from sklearn.metrics import mean_squared_error 

MSE = mean_squared_error(ans, pred_ada) 
np.sqrt(MSE)

## 모델링 #3 - XGBoost

In [ ]:
from xgboost import XGBRegressor

xgb_params = {'n_estimators' : [1000]}
xgb_reg = XGBRegressor(n_estimators=1000, learning_rate=0.05, colsample_bytree=0.5, subsample=0.8)
xgb_reg.fit(train_data,train_target_sc['wl_1018662'])

In [ ]:
pred_662 = xgb_reg.predict(test_data)
pred_662

In [ ]:
from xgboost import XGBRegressor

xgb_params = {'n_estimators' : [1000]}
xgb_reg = XGBRegressor(n_estimators=1000, learning_rate=0.05, colsample_bytree=0.5, subsample=0.8)
xgb_reg.fit(train_data,train_target_sc['wl_1018680'])

pred_680 = xgb_reg.predict(test_data)
pred_680

In [ ]:
from xgboost import XGBRegressor

xgb_params = {'n_estimators' : [1000]}
xgb_reg = XGBRegressor(n_estimators=1000, learning_rate=0.05, colsample_bytree=0.5, subsample=0.8)
xgb_reg.fit(train_data,train_target_sc['wl_1018683'])

pred_683 = xgb_reg.predict(test_data)
pred_683

In [ ]:
from xgboost import XGBRegressor

xgb_params = {'n_estimators' : [1000]}
xgb_reg = XGBRegressor(n_estimators=1000, learning_rate=0.05, colsample_bytree=0.5, subsample=0.8)
xgb_reg.fit(train_data,train_target_sc['wl_1019630'])

pred_683 = xgb_reg.predict(test_data)
pred_683

In [ ]:
pred_xg = np.stack((pred_662, pred_680, pred_683, pred_630), axis=1)
pred_xg

In [ ]:
inverse_xg = mMscaler2.inverse_transform(pred_xg) ## 원 데이터의 스케일로 변환
inverse_xg

In [ ]:
pred_xg = pd.DataFrame(inverse_xg, columns=train_target.columns)
pred_xg.head()

In [ ]:
MSE = mean_squared_error(ans, pred_xg) 
np.sqrt(MSE)

## 모델링 #4 - LightGBM 

In [ ]:
from sklearn.model_selection import KFold
from lightgbm import LGBMRegressor
kfold = KFold(n_splits=2, shuffle=True)

lgbm = LGBMRegressor()

params = {
    "num_leaves" : (20,40,60,80,100),
    "min_child_samples" : (5,10,15),
    "max_depth" : (-1,5,10,20),
    "learning_rate" : (0.05,0.1,0.2),
    "reg_alpha" : (0,0.01,0.03)
}

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_cv = GridSearchCV(lgbm,
                       param_grid=params,
                       cv = kfold,
                       n_jobs=-1)

In [ ]:
grid_cv.fit(train_data,train_target_sc['wl_1018662'])

GridSearchCV(cv=KFold(n_splits=2, random_state=None, shuffle=True),
             estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'learning_rate': (0.05, 0.1, 0.2),
                         'max_depth': (-1, 5, 10, 20),
                         'min_child_samples': (5, 10, 15),
                         'num_leaves': (20, 40, 60, 80, 100),
                         'reg_alpha': (0, 0.01, 0.03)})

In [ ]:
model_lgbm1 = grid_cv.best_estimator_
model_lgbm1.fit(train_data, train_target_sc['wl_1018662'])

LGBMRegressor(learning_rate=0.2, min_child_samples=15, num_leaves=100,
              reg_alpha=0)

In [ ]:
y_pred_662 = model_lgbm1.predict(test_data)

In [ ]:
grid_cv.fit(train_data,train_target_sc['wl_1018680'])

GridSearchCV(cv=KFold(n_splits=2, random_state=None, shuffle=True),
             estimator=LGBMRegressor(), n_jobs=-1,
             param_grid={'learning_rate': (0.05, 0.1, 0.2),
                         'max_depth': (-1, 5, 10, 20),
                         'min_child_samples': (5, 10, 15),
                         'num_leaves': (20, 40, 60, 80, 100),
                         'reg_alpha': (0, 0.01, 0.03)})

In [ ]:
model_lgbm2 = grid_cv.best_estimator_
model_lgbm2.fit(train_data, train_target_sc['wl_1018680'])

LGBMRegressor(learning_rate=0.2, min_child_samples=5, num_leaves=100,
              reg_alpha=0.01)

In [ ]:
y_pred_680 = model_lgbm2.predict(test_data)

In [ ]:
grid_cv.fit(train_data,train_target_sc['wl_1018683'])

model_lgbm3 = grid_cv.best_estimator_
model_lgbm3.fit(train_data, train_target_sc['wl_1018683'])

y_pred_683 = model_lgbm3.predict(test_data)

In [ ]:
grid_cv.fit(train_data,train_target_sc['wl_1019630'])

model_lgbm4 = grid_cv.best_estimator_
model_lgbm4.fit(train_data, train_target_sc['wl_1019630'])

y_pred_630 = model_lgbm4.predict(test_data)

In [ ]:
pred_lgbm = np.stack((y_pred_662, y_pred_680, y_pred_683, y_pred_630), axis=1)
pred_lgbm

array([[0.02018856, 0.03055013, 0.02956967, 0.04569043],
       [0.02069742, 0.03201176, 0.0299946 , 0.04392968],
       [0.02151133, 0.03186468, 0.02971847, 0.0399029 ],
       ...,
       [0.03061231, 0.05770238, 0.06980205, 0.11386033],
       [0.04668771, 0.06410403, 0.07612643, 0.11466856],
       [0.05904787, 0.07062213, 0.07992634, 0.11923347]])

In [ ]:
inverse_lgbm = mMscaler2.inverse_transform(pred_lgbm) ## 원 데이터의 스케일로 변환
inverse_lgbm

array([[280.45383543, 273.69512147, 271.63153379, 268.80564031],
       [280.97694425, 275.01058052, 271.98550154, 267.74566747],
       [281.81364603, 274.87821445, 271.7554871 , 265.32154548],
       ...,
       [291.16945278, 298.13214422, 305.1451058 , 309.84392058],
       [307.69496617, 303.89362933, 310.41331389, 310.33047364],
       [320.40120597, 309.75991411, 313.57863974, 313.07855086]])

In [ ]:
pred_lgbm = pd.DataFrame(inverse_lgbm, columns=train_target.columns)
pred_lgbm.head()

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0  280.453835  273.695121  271.631534  268.805640
1  280.976944  275.010581  271.985502  267.745667
2  281.813646  274.878214  271.755487  265.321545
3  285.098225  276.753776  273.551924  262.604791
4  285.665918  273.531917  271.470978  259.865507

In [ ]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(ans, pred_lgbm) 
np.sqrt(MSE)

4.34574760215609

In [ ]:
#y_pred_662, y_pred_680, y_pred_683, y_pred_630

print(np.sqrt(mean_squared_error(ans['wl_1018662'], pred_lgbm['wl_1018662'])))
print(np.sqrt(mean_squared_error(ans['wl_1018680'], pred_lgbm['wl_1018680'])))
print(np.sqrt(mean_squared_error(ans['wl_1018683'], pred_lgbm['wl_1018683'])))
print(np.sqrt(mean_squared_error(ans['wl_1019630'], pred_lgbm['wl_1019630'])))

4.705835413110702
5.9409483308076885
3.8383819112126107
1.835526950399794


In [ ]:
pred_lgbm.to_csv('/content/drive/MyDrive/Colab Notebooks/데이콘/lgbm.csv')

In [ ]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(ans, pred_lgbm) 
np.sqrt(MSE)

In [ ]:
from lightgbm import LGBMRegressor

lgbm_params = {'n_estimators' : [1000]}
lgbm_reg = LGBMRegressor(n_estimators=1000, learning_rate=0.05, num_leaves=4, colsample_bytree=0.4, subsample=0.6, reg_lambda=10, n_jobs=-1)
lgbm_reg.fit(train_data,train_target_sc['wl_1018662'])

pred_662 = lgbm_reg.predict(test_data)
pred_662

array([0.02101161, 0.02212089, 0.02342571, ..., 0.03155916, 0.04317945,
       0.05677734])

In [ ]:
lgbm_params = {'n_estimators' : [1000]}
lgbm_reg = LGBMRegressor(n_estimators=1000, learning_rate=0.05, num_leaves=4, colsample_bytree=0.4, subsample=0.6, reg_lambda=10, n_jobs=-1)
lgbm_reg.fit(train_data,train_target_sc['wl_1018680'])

pred_680 = lgbm_reg.predict(test_data)
pred_680

array([0.02920389, 0.03227465, 0.02901359, ..., 0.05764452, 0.0659504 ,
       0.07402526])

In [ ]:
lgbm_params = {'n_estimators' : [1000]}
lgbm_reg = LGBMRegressor(n_estimators=1000, learning_rate=0.05, num_leaves=4, colsample_bytree=0.4, subsample=0.6, reg_lambda=10, n_jobs=-1)
lgbm_reg.fit(train_data,train_target_sc['wl_1018683'])

pred_683 = lgbm_reg.predict(test_data)
pred_683

array([0.02846827, 0.03120879, 0.02962075, ..., 0.06295439, 0.07230968,
       0.07913041])

In [ ]:
lgbm_params = {'n_estimators' : [1000]}
lgbm_reg = LGBMRegressor(n_estimators=1000, learning_rate=0.05, num_leaves=4, colsample_bytree=0.4, subsample=0.6, reg_lambda=10, n_jobs=-1)
lgbm_reg.fit(train_data,train_target_sc['wl_1019630'])

pred_630 = lgbm_reg.predict(test_data)
pred_630

array([0.04427012, 0.0427195 , 0.0404043 , ..., 0.11336636, 0.11483258,
       0.11646082])

In [ ]:
pred_lgbm = np.stack((pred_662, pred_680, pred_683, pred_630), axis=1)
pred_lgbm

array([[0.02101161, 0.02920389, 0.02846827, 0.04427012],
       [0.02212089, 0.03227465, 0.03120879, 0.0427195 ],
       [0.02342571, 0.02901359, 0.02962075, 0.0404043 ],
       ...,
       [0.03155916, 0.05764452, 0.06295439, 0.11336636],
       [0.04317945, 0.0659504 , 0.07230968, 0.11483258],
       [0.05677734, 0.07402526, 0.07913041, 0.11646082]])

In [ ]:
inverse_lgbm = mMscaler2.inverse_transform(pred_lgbm) ## 원 데이터의 스케일로 변환
inverse_lgbm

array([[281.29993628, 272.48350382, 270.71407156, 267.95060972],
       [282.44027784, 275.2471881 , 272.99692443, 267.01713965],
       [283.78163159, 272.3122281 , 271.6740846 , 265.62338865],
       ...,
       [292.1428165 , 298.08007226, 299.44101027, 309.54654808],
       [304.08847128, 305.55536068, 307.23396728, 310.42921351],
       [318.06710987, 312.82273189, 312.9156297 , 311.40941296]])

In [ ]:
pred_lgbm = pd.DataFrame(inverse_lgbm, columns=train_target.columns)
pred_lgbm.head()

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0  281.299936  272.483504  270.714072  267.950610
1  282.440278  275.247188  272.996924  267.017140
2  283.781632  272.312228  271.674085  265.623389
3  284.875113  274.312129  273.656070  262.832263
4  284.243719  270.188642  269.676832  260.934431

In [ ]:
MSE = mean_squared_error(ans, pred_lgbm) 
np.sqrt(MSE)

5.096011898519971

## 모델링 #5 - 라쏘

In [ ]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(train_data,train_target_sc['wl_1018662'])

pred_662 = lasso_reg.predict(test_data)
pred_662

In [ ]:
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(train_data,train_target_sc['wl_1018680'])

pred_680 = lasso_reg.predict(test_data)
pred_680

In [ ]:
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(train_data,train_target_sc['wl_1018683'])

pred_683 = lasso_reg.predict(test_data)
pred_683

In [ ]:
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(train_data,train_target_sc['wl_1019630'])

pred_630 = lasso_reg.predict(test_data)
pred_630

In [ ]:
pred_lasso = np.stack((pred_662, pred_680, pred_683, pred_630), axis=1)
pred_lasso

In [ ]:
inverse_lasso = mMscaler2.inverse_transform(pred_lasso) ## 원 데이터의 스케일로 변환
inverse_lasso

In [ ]:
pred_lasso = pd.DataFrame(inverse_lasso, columns=train_target.columns)
pred_lasso.head()

In [ ]:
MSE = mean_squared_error(ans, pred_lasso) 
np.sqrt(MSE)

## 스태킹 앙상블

In [ ]:
# 스태킹 앙상블 모델
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error

def get_stacking_base_datasets(model, X_train_n, y_train_n, X_test_n, n_folds):
  kf = KFold(n_splits=n_folds, shuffle=False)
  train_fold_pred = np.zeros((X_train_n.shape[0], 1))
  test_pred = np.zeros((X_test_n.shape[0], n_folds))
  print(model.__class__.__name__, ' model 시작')

  for folder_counter, (train_index, valid_index) in enumerate(kf.split(X_train_n)):
    print('\n 폴드 세트: ', folder_counter, ' 시작 ')
    X_tr = X_train_n[train_index]
    y_tr = y_train_n[train_index]
    X_te = X_train_n[valid_index]

    model.fit(X_tr, y_tr)

    train_fold_pred[valid_index, :] = model.predict(X_te).reshape(-1,1)
    test_pred[:, folder_counter] = model.predict(X_test_n)

  test_pred_mean = np.mean(test_pred, axis=1).reshape(-1,1)

  return train_fold_pred, test_pred_mean

In [ ]:
X_train_n = train_data.values
X_test_n = test_data.values
y_train_n = train_target_sc['wl_1018662'].values

rf_train, rf_test = get_stacking_base_datasets(model_rf, X_train_n, y_train_n, X_test_n, 5)
#lasso_train, lasso_test = get_stacking_base_datasets(lasso_reg, X_train_n, y_train_n, X_test_n, 5)
#xgb_train, xgb_test = get_stacking_base_datasets(xgb_reg, X_train_n, y_train_n, X_test_n, 5)
lgbm_train, lgbm_test = get_stacking_base_datasets(model_lgbm1, X_train_n, y_train_n, X_test_n, 5)

RandomForestRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 
LGBMRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 


In [ ]:
Stack_final_X_train = np.concatenate((rf_train, lgbm_train), axis=1)
Stack_final_X_test = np.concatenate((rf_test, lgbm_test), axis=1)

meta_model_lgbm = LGBMRegressor(n_jobs=-1)

meta_model_lgbm.fit(Stack_final_X_train, y_train_n)
final1 = meta_model_lgbm.predict(Stack_final_X_test)
final1

array([0.01950098, 0.0196737 , 0.02122898, ..., 0.03117023, 0.04755282,
       0.05979327])

In [ ]:
X_train_n = train_data.values
X_test_n = test_data.values
y_train_n = train_target_sc['wl_1018680'].values

rf_train, rf_test = get_stacking_base_datasets(model_rf, X_train_n, y_train_n, X_test_n, 5)
#lasso_train, lasso_test = get_stacking_base_datasets(lasso_reg, X_train_n, y_train_n, X_test_n, 5)
#xgb_train, xgb_test = get_stacking_base_datasets(xgb_reg, X_train_n, y_train_n, X_test_n, 5)
lgbm_train, lgbm_test = get_stacking_base_datasets(model_lgbm2, X_train_n, y_train_n, X_test_n, 5)

RandomForestRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 
LGBMRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 


In [ ]:
Stack_final_X_train = np.concatenate((rf_train, lgbm_train), axis=1)
Stack_final_X_test = np.concatenate((rf_test, lgbm_test), axis=1)

meta_model_lgbm = LGBMRegressor(n_jobs=-1)

meta_model_lgbm.fit(Stack_final_X_train, y_train_n)
final2 = meta_model_lgbm.predict(Stack_final_X_test)
final2

array([0.02638773, 0.02874945, 0.02705075, ..., 0.06455257, 0.06944206,
       0.07475436])

In [ ]:
X_train_n = train_data.values
X_test_n = test_data.values
y_train_n = train_target_sc['wl_1018683'].values

rf_train, rf_test = get_stacking_base_datasets(model_rf, X_train_n, y_train_n, X_test_n, 5)
#lasso_train, lasso_test = get_stacking_base_datasets(lasso_reg, X_train_n, y_train_n, X_test_n, 5)
#xgb_train, xgb_test = get_stacking_base_datasets(xgb_reg, X_train_n, y_train_n, X_test_n, 5)
lgbm_train, lgbm_test = get_stacking_base_datasets(model_lgbm3, X_train_n, y_train_n, X_test_n, 5)

RandomForestRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 
LGBMRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 


In [ ]:
Stack_final_X_train = np.concatenate((rf_train, lgbm_train), axis=1)
Stack_final_X_test = np.concatenate((rf_test, lgbm_test), axis=1)

meta_model_lgbm = LGBMRegressor(n_jobs=-1)

meta_model_lgbm.fit(Stack_final_X_train, y_train_n)
final3 = meta_model_lgbm.predict(Stack_final_X_test)
final3

array([0.02972204, 0.02999651, 0.02992127, ..., 0.06977474, 0.07702801,
       0.08141121])

In [ ]:
X_train_n = train_data.values
X_test_n = test_data.values
y_train_n = train_target_sc['wl_1019630'].values

rf_train, rf_test = get_stacking_base_datasets(model_rf, X_train_n, y_train_n, X_test_n, 5)
#lasso_train, lasso_test = get_stacking_base_datasets(lasso_reg, X_train_n, y_train_n, X_test_n, 5)
#xgb_train, xgb_test = get_stacking_base_datasets(xgb_reg, X_train_n, y_train_n, X_test_n, 5)
lgbm_train, lgbm_test = get_stacking_base_datasets(model_lgbm4, X_train_n, y_train_n, X_test_n, 5)

RandomForestRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 
LGBMRegressor  model 시작

 폴드 세트:  0  시작 

 폴드 세트:  1  시작 

 폴드 세트:  2  시작 

 폴드 세트:  3  시작 

 폴드 세트:  4  시작 


In [ ]:
Stack_final_X_train = np.concatenate((rf_train, lgbm_train), axis=1)
Stack_final_X_test = np.concatenate((rf_test, lgbm_test), axis=1)

meta_model_lgbm = LGBMRegressor(n_jobs=-1)

meta_model_lgbm.fit(Stack_final_X_train, y_train_n)
final4 = meta_model_lgbm.predict(Stack_final_X_test)
final4

array([0.04588772, 0.04312919, 0.0399931 , ..., 0.11382282, 0.11564474,
       0.11773168])

In [ ]:
pred_stack = np.stack((final1, final2, final3, final4), axis=1)
pred_stack

array([[0.01950098, 0.02638773, 0.02972204, 0.04588772],
       [0.0196737 , 0.02874945, 0.02999651, 0.04312919],
       [0.02122898, 0.02705075, 0.02992127, 0.0399931 ],
       ...,
       [0.03117023, 0.06455257, 0.06977474, 0.11382282],
       [0.04755282, 0.06944206, 0.07702801, 0.11564474],
       [0.05979327, 0.07475436, 0.08141121, 0.11773168]])

In [ ]:
inverse_stack = mMscaler2.inverse_transform(pred_stack) ## 원 데이터의 스케일로 변환
inverse_stack

array([[279.747003  , 269.94895457, 271.75845657, 268.92440516],
       [279.92456666, 272.07450222, 271.98709333, 267.26377378],
       [281.52338978, 270.54567814, 271.92441488, 265.37584737],
       ...,
       [291.74299406, 304.29731315, 305.1223565 , 309.82133735],
       [308.58429493, 308.69785099, 311.16433635, 310.9181346 ],
       [321.16747862, 313.47892743, 314.81553388, 312.17447285]])

In [ ]:
pred_stack = pd.DataFrame(inverse_stack, columns=train_target.columns)
pred_stack.head()

wl_1018662  wl_1018680  wl_1018683  wl_1019630
0  279.747003  269.948955  271.758457  268.924405
1  279.924567  272.074502  271.987093  267.263774
2  281.523390  270.545678  271.924415  265.375847
3  284.496942  273.211259  272.766690  262.391535
4  285.750657  271.674658  271.104468  259.810754

In [ ]:
MSE = mean_squared_error(ans, pred_stack) 
np.sqrt(MSE)

7.344531384619922

In [ ]:
print(np.sqrt(mean_squared_error(ans['wl_1018662'], pred_stack['wl_1018662'])))
print(np.sqrt(mean_squared_error(ans['wl_1018680'], pred_stack['wl_1018680'])))
print(np.sqrt(mean_squared_error(ans['wl_1018683'], pred_stack['wl_1018683'])))
print(np.sqrt(mean_squared_error(ans['wl_1019630'], pred_stack['wl_1019630'])))

7.411617519596668
9.444202980787372
7.017824698785424
4.732193712928519
